import {
  Campaign,
  Customer,
  DeliveryLog,
  DeviceStatus,
  EventRecord,
  Template,
} from "@/types";

export const customers: Customer[] = [
  {
    id: "C-1001",
    name: "Olivia Carter",
    company: "South Coast Realty",
    mobile: "+61 412 334 810",
    email: "olivia@southcoastrealty.au",
    city: "Sydney",
    tags: ["VIP", "Event"],
    eventCount: 4,
    consentSms: true,
    consentEmail: true,
    lastContact: "2026-04-15 09:15",
  },
  {
    id: "C-1002",
    name: "Liam Mitchell",
    company: "Harbour Fitness",
    mobile: "+61 433 702 194",
    email: "liam@harbourfitness.au",
    city: "Melbourne",
    tags: ["Prospect"],
    eventCount: 1,
    consentSms: true,
    consentEmail: false,
    lastContact: "2026-04-11 17:42",
  },
  {
    id: "C-1003",
    name: "Amelia Brooks",
    company: "Brookside Dental",
    mobile: "+61 401 258 901",
    email: "amelia@brookside.au",
    city: "Brisbane",
    tags: ["Repeat", "Email"],
    eventCount: 5,
    consentSms: true,
    consentEmail: true,
    lastContact: "2026-04-17 13:20",
  },
  {
    id: "C-1004",
    name: "Noah Singh",
    company: "Blue Terrain Travel",
    mobile: "+61 422 844 905",
    email: "noah@blueterrain.au",
    city: "Perth",
    tags: ["Dormant"],
    eventCount: 0,
    consentSms: false,
    consentEmail: true,
    lastContact: "2026-03-29 08:05",
  },
  {
    id: "C-1005",
    name: "Charlotte Evans",
    company: "Sunline Events",
    mobile: "+61 478 222 631",
    email: "charlotte@sunlineevents.au",
    city: "Adelaide",
    tags: ["VIP", "Repeat"],
    eventCount: 7,
    consentSms: true,
    consentEmail: true,
    lastContact: "2026-04-18 19:03",
  },
  {
    id: "C-1006",
    name: "Ethan Walker",
    company: "Walker Auto Care",
    mobile: "+61 491 300 214",
    email: "ethan@walkerautocare.au",
    city: "Gold Coast",
    tags: ["SMS"],
    eventCount: 2,
    consentSms: true,
    consentEmail: true,
    lastContact: "2026-04-14 12:34",
  },
];

export const events: EventRecord[] = [
  {
    id: "EV-210",
    title: "Autumn VIP Preview",
    date: "2026-04-28 18:30",
    venue: "Sydney Showroom",
    audience: "VIP Customers",
    smsTemplate: "Hi {{name}}, you're invited to our Autumn VIP Preview on 28 April.",
    emailSubject: "Your VIP invitation for 28 April",
    status: "Scheduled",
  },
  {
    id: "EV-211",
    title: "EOFY Member Offer",
    date: "2026-06-12 09:00",
    venue: "Online Campaign",
    audience: "All SMS Contacts",
    smsTemplate: "EOFY event starts soon. Reply YES to reserve your slot.",
    emailSubject: "EOFY event early access",
    status: "Draft",
  },
  {
    id: "EV-212",
    title: "Referral Breakfast",
    date: "2026-05-05 08:00",
    venue: "Melbourne Central",
    audience: "Partners",
    smsTemplate: "Quick reminder: referral breakfast is on 5 May at 8am.",
    emailSubject: "Referral breakfast reminder",
    status: "Completed",
  },
];

export const campaigns: Campaign[] = [
  {
    id: "CA-501",
    name: "Autumn VIP SMS",
    channel: "SMS",
    audienceSize: 240,
    sent: 197,
    failed: 5,
    owner: "Pulak",
    launchedAt: "2026-04-19 10:20",
    status: "Sending",
  },
  {
    id: "CA-502",
    name: "EOFY Early Access Email",
    channel: "Email",
    audienceSize: 820,
    sent: 820,
    failed: 12,
    owner: "Pulak",
    launchedAt: "2026-04-16 14:45",
    status: "Completed",
  },
  {
    id: "CA-503",
    name: "Referral Breakfast SMS",
    channel: "SMS",
    audienceSize: 66,
    sent: 0,
    failed: 0,
    owner: "Pulak",
    launchedAt: "2026-04-21 08:00",
    status: "Queued",
  },
];

export const templates: Template[] = [
  {
    id: "TP-1",
    name: "VIP Event Reminder",
    channel: "SMS",
    body: "Hi {{name}}, reminder that our event starts at {{time}}. Reply STOP to opt out.",
    updatedAt: "2026-04-18",
  },
  {
    id: "TP-2",
    name: "General Event Invite",
    channel: "Email",
    body: "Hello {{name}},\n\nWe'd love to see you at our upcoming event on {{date}}.\n\nRegards,\nTeam",
    updatedAt: "2026-04-17",
  },
  {
    id: "TP-3",
    name: "Same-Day SMS Alert",
    channel: "SMS",
    body: "Hi {{name}}, today's event starts in 2 hours. See you there.",
    updatedAt: "2026-04-15",
  },
];

export const deviceStatus: DeviceStatus = {
  deviceName: "Pulak's Galaxy A55",
  phoneNumber: "+61 422 111 909",
  operator: "Telstra AU",
  status: "Online",
  lastSeen: "2026-04-19 11:56",
  queuedJobs: 43,
  battery: "78%",
};

export const deliveryLogs: DeliveryLog[] = [
  {
    id: "LG-1",
    customer: "Olivia Carter",
    channel: "SMS",
    campaign: "Autumn VIP SMS",
    timestamp: "2026-04-19 11:40",
    status: "Sent",
    detail: "Delivered through device Pulak's Galaxy A55",
  },
  {
    id: "LG-2",
    customer: "Liam Mitchell",
    channel: "SMS",
    campaign: "Autumn VIP SMS",
    timestamp: "2026-04-19 11:41",
    status: "Failed",
    detail: "Carrier rejected due to invalid number format",
  },
  {
    id: "LG-3",
    customer: "Amelia Brooks",
    channel: "Email",
    campaign: "EOFY Early Access Email",
    timestamp: "2026-04-16 15:02",
    status: "Sent",
    detail: "SMTP accepted and provider id queued",
  },
  {
    id: "LG-4",
    customer: "Charlotte Evans",
    channel: "SMS",
    campaign: "Referral Breakfast SMS",
    timestamp: "2026-04-19 11:52",
    status: "Queued",
    detail: "Waiting for phone dispatch batch",
  },
];

export const dashboardStats = [
  { label: "Total customers", value: "12,480", note: "+286 from latest import" },
  { label: "SMS ready contacts", value: "8,124", note: "Consented and valid AU mobile" },
  { label: "Emails sent this month", value: "18,940", note: "97.3% provider acceptance" },
  { label: "Live device queue", value: "43", note: "Pushed to your Android sender" },
];
